name: Deploy & Audit Website

on:
  push:
    branches:
      - main
      - daffa

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy-url: ${{ steps.vercel_deploy.outputs.deploy-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        id: vercel_deploy
        run: |
          echo "Deploying to Vercel..."
          # Matikan telemetry agar output bersih
          export NOW_TELEMETRY_DISABLED=1

          if [ "${GITHUB_REF##*/}" = "main" ]; then
            # Deploy ke production
            DEPLOY_URL=$(vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --output=plain)
          else
            # Deploy ke preview untuk branch lain
            DEPLOY_URL=$(vercel --token=${{ secrets.VERCEL_TOKEN }} --confirm --output=plain)
          fi

          echo "deploy-url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  lighthouse:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: |
          echo "Running Lighthouse on deployed URL..."
          lhci collect --url="${{ needs.deploy.outputs.deploy-url }}" || true
          lhci assert || true
          lhci upload || true
