name: Deploy & Audit Website

on:
  push:
    branches:
      - main
      - daffa

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy-url: ${{ steps.set-url.outputs.deploy-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        id: vercel_deploy
        run: |
          echo "Deploying to Vercel..."
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            DEPLOY_URL=$(vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --scope ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_PROJECT_ID }} 2>&1 || echo "ERROR")
          else
            DEPLOY_URL=$(vercel --token=${{ secrets.VERCEL_TOKEN }} --confirm --scope ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_PROJECT_ID }} 2>&1 || echo "ERROR")
          fi

          # Debug output
          echo "Vercel deploy result: $DEPLOY_URL"

          # Set output hanya jika deploy sukses
          if [[ "$DEPLOY_URL" != "ERROR" ]]; then
            echo "deploy-url=$DEPLOY_URL" >> $GITHUB_OUTPUT
          else
            echo "deploy-url=" >> $GITHUB_OUTPUT
          fi
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Set deploy URL output
        id: set-url
        run: echo "deploy-url=${{ steps.vercel_deploy.outputs.deploy-url }}" >> $GITHUB_OUTPUT

  lighthouse:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: |
          URL=${{ needs.deploy.outputs.deploy-url }}
          if [ -z "$URL" ]; then
            echo "No deploy URL found, skipping Lighthouse CI."
          else
            lhci collect --url="$URL"
            lhci assert || true
            lhci upload || true
          fi
