name: Deploy & Audit Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy-url: ${{ steps.vercel_deploy.outputs.deploy-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        id: vercel_deploy
        run: |
          echo "Deploying to Vercel..."
          # Deploy ke Vercel, filter note supaya tidak mengacaukan $GITHUB_OUTPUT
          DEPLOY_URL=$(vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm 2>&1 | grep -v "NOTE: The Vercel CLI now collects telemetry")
          echo "deploy-url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  lighthouse:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: |
          echo "Running Lighthouse on deployed URL..."
          lhci collect --url="${{ needs.deploy.outputs.deploy-url }}" || true
          lhci assert || true
          lhci upload || true
